FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["/EShop.Web/EShop.Web.csproj", "/src/EShop.Web/"]
COPY ["/Logger/Logger.csproj", "/src/Logger/"]

RUN dotnet restore "EShop.Web/EShop.Web.csproj"

COPY . .
WORKDIR /src/EShop.Web
RUN dotnet build "EShop.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EShop.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish . 
ENTRYPOINT ["dotnet", "EShop.Web.dll"]